version: '3.8'
services:

  redis:
    image: "redis"
    command: redis-server
    ports:
      - "6378:6379"
    networks:
      - WithGithubaction

  db:
    image: "postgres"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"

    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - WithGithubaction

  server:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
      REDIS_URL: 'redis://redis:6379'
      SESSION_SECRET: "sinnerman"
      PORT: '5000'
      ORIGIN : "http://localhost:3000"
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      -  /app/node_modules
      - /app/dist
    links :
      - redis
      - db
    networks:
      - WithGithubaction

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      backend_url: "http://localhost:5000/graphql"
    volumes:
      - ./frontend:/app
      #don't bind this foler with host
      - /app/node_modules
      - /app/.next
    networks:
      - WithGithubaction

networks:
 WithGithubaction:
  driver: bridge
volumes:
  db-data:
  watchtower:
    driver: local