version: '3.8'
services:

  redis:
    image: "redis"
    command: redis-server
    ports:
      - "6378:6379"
    networks:
      - WithGithubaction

  db:
    image: "postgres"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"

    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - WithGithubaction

  server:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
      REDIS_URL: 'redis://redis:6379'
      SESSION_SECRET: "sinnerman"
      PORT: '5000'
      ORIGIN : "https://frontdev.localhost"
    ports:
      - "5000:5000"
    links :
      - redis
      - db
    networks:
      - WithGithubaction

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      backend_url: "https://milldev.localhost/graphql"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - WithGithubaction

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - WithGithubaction

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

networks:
 WithGithubaction:
  driver: bridge
volumes:
  db-data:
  caddy:
  watchtower:
    driver: local