name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - "v*"



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker image backend
      working-directory: ./backend
      run: |
        docker build -t ekaluk52003/invoicepromptapi:pre-production .

    - name: docker push backend
      working-directory: ./backend
      run: |
        docker push ekaluk52003/invoicepromptapi:pre-production

    - name: Build Docker image frontend
      working-directory: ./frontend
      run: |
        docker build -t ekaluk52003/invoicepromptfrontend:pre-production .

    - name: docker push frontend
      working-directory: ./frontend
      run: |
        docker push ekaluk52003/invoicepromptfrontend:pre-production





